name: Build Kubernets configmap

on:
  push:

jobs:
  build-configmap:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/setup-kubectl@v1
      - uses: FranzDiebold/github-env-vars-action@v2
      - uses: actions/checkout@v2
      - run: |
          kubectl create configmap $CI_REPOSITORY_NAME \
            --from-file=kong/plugins/request-firewall \
            --dry-run=client \
            --output=yaml > $CI_REPOSITORY_NAME.yaml
      - uses: eine/tip@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            *.yaml
